#!/bin/bash
set -eo pipefail

. versions

refLatest="AST_${AST_LATEST}"
docker build --build-arg asterisk_version=${!refLatest} -t $IMAGE_NAME .

for v in ${AST_VERSIONS}; do
    refVersion="AST_${v}"
    docker build --build-arg asterisk_version=${!refVersion} -t $DOCKER_REPO:${!refVersion} .
done
