#!/bin/sh
docker tag $IMAGE_NAME $DOCKER_REPO:16
docker tag $IMAGE_NAME $DOCKER_REPO:16.8.0
docker push $DOCKER_REPO:16
docker push $DOCKER_REPO:16.8.0

docker tag $DOCKER_REPO:17.2.0 $DOCKER_REPO:17
docker push $DOCKER_REPO:17
docker push $DOCKER_REPO:17.2.0
